class_name TerrainMasses
extends Node2D
## The map's rock in physics: one static body per mass named by a [TerrainShape],
## plus the wall around the edge of the walkable desert.
##
## [b]It builds what was already authored, and invents nothing.[/b] Every shape
## here is an outline out of [member shape] - the same outlines
## [WorldMapNavigation] bakes its mesh from and [PropScatter] keeps its scenery
## out of - so what the player's body is stopped by cannot drift out of step with
## what the bandits path around or where the cacti stand. A map whose rock moves
## is a re-traced [TerrainShape] and nothing else.
##
## [b]The bodies are made rather than authored.[/b] Three hundred points of
## outline is not something to keep as three hundred lines of scene file that
## have to be regenerated by hand; the resource is the authored thing and this
## node is how it becomes collision. Building happens once, as the map loads.

## Group this node joins, so anything that wants the map's authored ground plan
## can find it without a path across the scene - the same lookup convention
## [WorldMapFog], [WorldMapState] and [WorldMapLocationDirector] already use. It
## is what lets [WorldMapScreen], which lives on the HUD rather than in the map
## scene, draw the region from the very outlines the collision here is built
## from, instead of measuring the ground a second way.
const GROUP := &"terrain_masses"

## The ground plan this builds. Nothing is built when it is empty, which is what
## a scene opened on its own in the editor sees.
@export var shape: TerrainShape

## Physics layer the rock sits on. 32 is the project's [code]prop_solid[/code]
## layer - the one the player's body and the bandits' sightlines already look
## for - so the rock stops movement and blocks vision with nothing rewired.
@export_flags_2d_physics var terrain_layer: int = 32

## Whether the wall around [member TerrainShape.walkable_outline] is built.
## The edge of the desert is a line rather than a slab: it is built as segments,
## so the body is the boundary itself and not the entire outside of the map.
@export var builds_boundary: bool = true

## Group each rock mass joins, for anything that wants to find the map's
## obstacles. Left empty by default: [PropScatter] is kept clear of the rock by
## being handed the same [member shape], which is exact, rather than by the
## group's bounding-box clearance, which for masses this large and this concave
## would blank out most of the map.
@export var mass_group: StringName = &""

## Whether the bodies are built as the map loads. Off is for a scene that wants
## to call [method build] itself.
@export var build_on_ready: bool = true

@export_group("Look")
## The texture the whole ground plan is painted with. Leave it empty and this
## node stays what it has always been - collision and nothing else - which is
## what every map that draws its ground some other way sees.
##
## [b]One texture covers all three layers.[/b] The desert, the rock standing in
## it and the rock surrounding it are the same artwork at different tints, so a
## map's ground is one asset in the inspector rather than a set of images that
## have to be drawn to agree with each other. What separates rock from sand is
## [member rock_tint], and what shapes it is [member shape] - the very outlines
## the bodies above are built from, so the rock the player is stopped by is by
## construction the rock they can see.
@export var ground_texture: Texture2D
## How many world pixels one tile of [member ground_texture] covers. The main
## size dial, and the same one [TiledSurface] offers: larger is coarser ground
## and fewer repeats.
@export var ground_tile_size: float = 1000.0
## Tints the walkable desert. White leaves the artwork as it was drawn.
@export var ground_tint: Color = Color.WHITE
## Tints the rock - both the masses and the terrain surrounding the desert.
## Below white, so the rock reads darker than the sand it stands in.
@export var rock_tint: Color = Color(0.686, 0.714, 0.696)

@export_subgroup("Layers")
## Draw order of the rock surrounding the walkable desert, under everything.
@export var surround_z_index: int = -15
## Draw order of the walkable desert itself. Sits on the surround.
@export var ground_z_index: int = -14
## Draw order of the rock masses. Sits on the desert, under every prop.
@export var mass_z_index: int = -13

## How many mass bodies currently stand under this node.
var _built: int = 0


func _enter_tree() -> void:
	add_to_group(GROUP)


func _ready() -> void:
	if build_on_ready:
		build()


## The ground plan of the map currently in the tree, found by group. Null means
## there is no authored terrain to read - a scene opened on its own, or a map
## that draws its ground some other way - which every caller reads as "there is
## nothing to draw".
static func get_active_shape(from_node: Node) -> TerrainShape:
	if from_node == null or not from_node.is_inside_tree():
		return null
	var masses := from_node.get_tree().get_first_node_in_group(GROUP) as TerrainMasses
	return null if masses == null else masses.shape


## Builds - or rebuilds - every body from [member shape]. Answers how many rock
## masses were made. Safe to call again; whatever was built before is cleared
## first, so re-tracing a map and calling this once is the whole update.
func build() -> int:
	for child: Node in get_children():
		child.queue_free()
	_built = 0
	if shape == null:
		return 0

	for index: int in shape.masses.size():
		var outline: PackedVector2Array = shape.masses[index]
		if outline.size() < 3:
			continue
		_add_body("Mass%d" % (index + 1), outline, CollisionPolygon2D.BUILD_SOLIDS, mass_group)
		_built += 1

	if builds_boundary and shape.walkable_outline.size() >= 3:
		_add_body("Boundary", shape.walkable_outline, CollisionPolygon2D.BUILD_SEGMENTS, &"")

	_paint()
	return _built


## How many rock masses this node built.
func get_mass_count() -> int:
	return _built


func _add_body(
		body_name: String,
		outline: PackedVector2Array,
		build_mode: CollisionPolygon2D.BuildMode,
		group: StringName) -> void:
	var body := StaticBody2D.new()
	body.name = body_name
	body.collision_layer = terrain_layer
	body.collision_mask = 0
	if group != &"":
		body.add_to_group(group)
	add_child(body)

	var polygon := CollisionPolygon2D.new()
	polygon.name = "Shape"
	polygon.build_mode = build_mode
	polygon.polygon = outline
	body.add_child(polygon)


## Paints the ground plan: the rock surrounding the desert, the walkable desert
## laid over it, and the rock masses laid over that.
##
## [b]The art is built from the outlines rather than drawn to match them.[/b] A
## painted map would be one image that has to be re-exported whenever the plan is
## re-traced, and that quietly becomes the second place the map's shape is
## written down - so a mass moved in [member shape] would leave rock the player
## can see and walk through, or ground they can see and cannot reach. Reading the
## same resource the bodies are built from makes that impossible.
##
## Three flat layers rather than a cut-out ring, because [Polygon2D] fills an
## outline and has no notion of a hole: the surround is the whole of
## [member TerrainShape.bounds] in rock, and the desert is simply painted back
## over the middle of it.
func _paint() -> void:
	if ground_texture == null or shape == null:
		return

	var bounds := shape.bounds
	_add_art("Surround", PackedVector2Array([
		bounds.position,
		Vector2(bounds.end.x, bounds.position.y),
		bounds.end,
		Vector2(bounds.position.x, bounds.end.y),
	]), rock_tint, surround_z_index)

	if shape.walkable_outline.size() >= 3:
		_add_art("Ground", shape.walkable_outline, ground_tint, ground_z_index)

	for index: int in shape.masses.size():
		var outline: PackedVector2Array = shape.masses[index]
		if outline.size() < 3:
			continue
		_add_art("Mass%dArt" % (index + 1), outline, rock_tint, mass_z_index)


## One painted layer. The texture is tiled through the polygon's own transform
## the same way [TiledSurface] does it, so [member ground_tile_size] means the
## same thing on a map's ground as it does on an arena's floor.
func _add_art(art_name: String, outline: PackedVector2Array, tint: Color, z: int) -> void:
	var art := Polygon2D.new()
	art.name = art_name
	art.polygon = outline
	art.color = tint
	art.z_index = z
	art.texture = ground_texture
	# Without this the texture is clamped and one tile is all that is ever drawn.
	art.texture_repeat = CanvasItem.TEXTURE_REPEAT_ENABLED
	art.texture_filter = CanvasItem.TEXTURE_FILTER_LINEAR_WITH_MIPMAPS
	# Polygon2D's scale is "how many times the texture fits", which is the
	# reciprocal of how much ground a tile covers.
	var tex := Vector2(ground_texture.get_size())
	var span := maxf(ground_tile_size, 0.001)
	art.texture_scale = Vector2(tex.x / span, tex.y / span)
	add_child(art)
